chore(deps): update dependency com.google.devtools.ksp to v2.0.0-1.0.22 (#316)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [com.google.devtools.ksp](https://goo.gle/ksp)
([source](https://togithub.com/google/ksp)) | `2.0.0-1.0.21` ->
`2.0.0-1.0.22` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/com.google.devtools.ksp/2.0.0-1.0.22?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/com.google.devtools.ksp/2.0.0-1.0.22?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/com.google.devtools.ksp/2.0.0-1.0.21/2.0.0-1.0.22?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/com.google.devtools.ksp/2.0.0-1.0.21/2.0.0-1.0.22?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>google/ksp (com.google.devtools.ksp)</summary>

###
[`v2.0.0-1.0.22`](https://togithub.com/google/ksp/releases/tag/2.0.0-1.0.22)

[Compare
Source](https://togithub.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22)

#### Important Changes

- `KSErrorType.toString()` now contains the reference name it was tried
to be resolved, and therefore `KSErrorType` is no longer a singleton.
Processors relying on equality checks of that (in contrast of using
`KSType.isError`) will need to be updated accordingly.

#### Issues Fixed

[#&#8203;1908](https://togithub.com/google/ksp/issues/1908) KSP2:
Calling KSP2 in programs does not appear to work on macOS or Windows
[#&#8203;1917](https://togithub.com/google/ksp/issues/1917) KSP2's
symbol-processing-aa-embeddable artifact exposes an unresolvable
pre-release kotlin 2.0.20 dependency
[#&#8203;1911](https://togithub.com/google/ksp/issues/1911)
NoSuchMethodError when running KSP2 with Dagger (KSP 2.0.0-1.0.21)
[#&#8203;1909](https://togithub.com/google/ksp/issues/1909) KSP2:
default annotation arguments no longer work in 1.0.21
[#&#8203;1232](https://togithub.com/google/ksp/issues/1232) Expose
simple names on a missing types's synthetic declaration
[#&#8203;1857](https://togithub.com/google/ksp/issues/1857) \[KSP2]
Modifiers are missing for property accessors
[#&#8203;1924](https://togithub.com/google/ksp/issues/1924) \[KSP2] Type
arg becomes '\*' after calling KSType.replace() with an error type
[#&#8203;1948](https://togithub.com/google/ksp/issues/1948) KSP2 default
annotation KClass values for built-in types use java.lang.\* versions

#### What's Changed

- Include type hint into KSErrorType. by
[@&#8203;Jeffset](https://togithub.com/Jeffset) in
[https://github.com/google/ksp/pull/1848](https://togithub.com/google/ksp/pull/1848)
- Implement Resolver.getModuleName API by
[@&#8203;ZacSweers](https://togithub.com/ZacSweers) in
[https://github.com/google/ksp/pull/1847](https://togithub.com/google/ksp/pull/1847)
- Patch AA service files in renamed uber jar by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1867](https://togithub.com/google/ksp/pull/1867)
- fix annotation default value parsing for arrays and class literals. by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1871](https://togithub.com/google/ksp/pull/1871)
- fix package name for library based symbols by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1873](https://togithub.com/google/ksp/pull/1873)
- Do not index classpath in declaration provider by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1870](https://togithub.com/google/ksp/pull/1870)
- check functional interface for modifiers by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1872](https://togithub.com/google/ksp/pull/1872)
- Annotation default java by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1879](https://togithub.com/google/ksp/pull/1879)
- fix type parameter bounds by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1880](https://togithub.com/google/ksp/pull/1880)
- Add command line parser and entry points by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1885](https://togithub.com/google/ksp/pull/1885)
- KSP2: Fix support of wasm by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1888](https://togithub.com/google/ksp/pull/1888)
- Return KSClassDeclarationEnumEntryImpl for enum entry annotation
values. by [@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1881](https://togithub.com/google/ksp/pull/1881)
- Reuse Kotlin indexes in incremental providers by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1891](https://togithub.com/google/ksp/pull/1891)
- special handling for java property accessors override checking by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1894](https://togithub.com/google/ksp/pull/1894)
- KSP2: Reuse Java indexes by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1895](https://togithub.com/google/ksp/pull/1895)
- Incremental: fix roots from getSealedSubclasses by
[@&#8203;ting-yuan](https://togithub.com/ting-yuan) in
[https://github.com/google/ksp/pull/1893](https://togithub.com/google/ksp/pull/1893)
- use safe cast for annotation type to declaration resolution by
[@&#8203;neetopia](https://togithub.com/neetopia) in
[https://github.com/google/ksp/pull/1902](https://togithub.com/google/ksp/pull/1902)

**Full Changelog**:
https://github.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/arrow-kt/arrow-website).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4zODguMSIsInVwZGF0ZWRJblZlciI6IjM3LjM4OC4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>